### ISSUE TITLE
Bootanimation isn't animated

### ISSUE THREAD

**Issue by bennihtm** [linuxmint/mint19.3-beta#21]
The Bootanimation isn't animated nor it shows dots under it.
That is confusing, because I thought that the Boot has crashed or isn't progressing.

**Comment by clefebvre** [comment]
Hi Ben,

There's a subtle animation inside of the logo. We call it the washing machine... the green turns around..

**Comment by LinuxOnTheDesktop** [comment]
Perhaps the animation should be made more overt. For I too failed to notice it, until, having seen this page, I looked for it. I suppose it depends on what the animation is for. Perhaps its purpose is

1) to enable those who suspect that there is a problem, to check whether there really is a problem, i.e. to check whether anything is happening.

Or perhaps the purpose is 

2) to reassure the normal user, who has no particular reason to think anything is wrong, that something is happening.

If the purpose is 1, then the current subtle animation is fine, although a worried user can, anyway, press a key to see what is going on - so I am unsure that purpose 1 needs serving. If the purpose is 2, then it seems to me that the subtle animation does not serve it. Still, perhaps on other systems - those with larger screens and/or no HiDPI - the animation is more visible.

EDIT: Also - though this is a small thing - should the animation _stop_ (or change colour?) when, on the live system, the user is told, 'Please remove the installation medium, then press ENTER:'? Perhaps, though, in order to encourage the user to think that she must do something, the colon at the end of the message should be replaced by `. . .`
