### ISSUE TITLE
grouped-window-list needs show all Windows of all Monitors and other features

### ISSUE THREAD

**Issue by NoXPhasma** [linuxmint/mint19.3-beta#32]
```
 * Cinnamon version 4.4.2
 * Distribution - (Mint 19.3 beta)
 * 64 bit
 ```

Issue

The applet now misses the option to show all windows of all monitors. This was present in 19.2 and it should come back. There are also other features you stripped out the applet like the space between the icons.

Steps to reproduce

Update to the 19.3 beta and add Grouped Window List applet

Expected behaviour

There should be an option to show all Windows on all monitors and to change the space between the icons.

**Comment by clefebvre** [comment]
No, the applet (just like window-list before it) detects whether there's an instance on the other monitor and acts accordingly.

The other features were removed on purpose because they were too niche and overkill. This has a cost in stability and in performance in the long run.

**Comment by NoXPhasma** [comment]
> No, the applet (just like window-list before it) detects whether there's an instance on the other monitor and acts accordingly.

But this feature was available in the applet before and the current behaviour was default as well. I don't see why it was needed to remove it. Just because you don't use it, doesn't mean there is no use case.

**Comment by collinss** [comment]
~~It would seem that there is still a setting to show windows on all monitors, but it doesn't actually do anything now. This is also the case with the old window list. Changing the setting has no effect on either applet.~~ Scratch that, I misread and the setting is actually for workspaces, not monitors.

@NoXPhasma We're not removing these features just because _we_ don't use them. We carefully weigh the pros and cons of each feature before we decide to remove it. With the grouped window list the problem that we're having is that there's way too many settings for a stock applet, and there's a cost for every setting. First, it's harder for the average user, because it becomes more of a burden to configure their desktop. Second, it almost always consumes more system resources. And third, it makes it much harder to maintain, and therefore more prone to bugs to have so many options. For these reasons, it is literally impossible to make everyone happy. Our strategy then is to try to make it 'just work' for 90% of our users, and then offer alternatives for the other 10% in the form of 3rd party applets, etc.

If you'd like to go back to the previous behavior, for now at least, you should be able to use an older version by copying the entire applet folder to ~/.local/share/cinnamon/applets/ or see if there's a 3rd party option in the 3rd party downloads that has the feature.

**Comment by NoXPhasma** [comment]
The only setting which is left, is to show windows of all work spaces. You probably confuse that with what I was talking about. Which also makes me wonder why that option does not make it harder for average users, but showing all windows from all monitors does.

Yes, I can override that applet as you suggest (which I already do), but this will eventually break when you change the API in the future.

**Comment by collinss** [comment]
> Yes, I can override that applet as you suggest (which I already do), but this will eventually break when you change the API in the future.

Yes, it's certainly not a long-term solution, though the applet it was forked from was quite popular before it was removed, so it's probably only a matter of time before someone forks it and puts it back up.
