### ISSUE TITLE
Thunar / Mint-Themes - Side bar colour is not consistent with theming for Caja and Nemo

### ISSUE THREAD

**Issue by smurphos** [linuxmint/mint19.3-beta#41]
Hi.

In 19.3 XFCE the Thunar sidebar is light coloured with the default Mint-Y theme. Caja and Nemo on the other hand have a dark sidebar.

I'd suggest amending https://github.com/linuxmint/mint-themes/blob/master/src/Mint-Y/gtk-3.0/sass/_applications.scss#L1000

to use  $dark_sidebar_bg and  $dark_sidebar_fg in line with the theme's colouring for other file managers.

The same issues also applies to Mint-X

Current theming with Mint-Y - Thunar on the left, Nemo and Caja on the right.

![screenshot-screen-2019-12-09-061215](https://user-images.githubusercontent.com/29017677/70411721-e62f8f00-1a4a-11ea-8a6c-8fac2365a4c8.png)

**Comment by clefebvre** [comment]
Eagle eyes :)

Anyway, that's done on purpose because Thunar uses fullcolor icons in its sidebar. The trash icon is dark on top of dark (same in Caja) but you can see it a bit.. the home icon on the other hand is very problematic here.

This should be reported directly to the Thunar devs imo. They already implemented symbolic icons in their toolbar, they should do so also in their sidebar. If they're hesitant to do so, they can make it configurable... on our side once Thunar uses symbolic icons, we can give it a nice dark background and it'll look just as nice as Nemo. In the meantime, this grey color does the trick.

**Comment by smurphos** [comment]
I can't claim to be that eagle-eyed. It came up in a discussion on the forums about how to best modify the theme to reinstate the dark sidebar.  I thought it was worth a report as the usual goal is visual consistency across the editions and Thunar had the dark sidebar in 19.2 with the GTK2 theme despite the icon issue.

Edit to add - there is an existing feature request on the XFCE bugzilla - https://bugzilla.xfce.org/show_bug.cgi?id=15685

**Comment by clefebvre** [comment]
Thanks.
