### ISSUE TITLE
Transmission client icons missing with Mint-Y Dark theme

### ISSUE THREAD

**Issue by MichalKolesinski** [linuxmint/mint19.3-beta#5]
![Transmission1](https://user-images.githubusercontent.com/39199872/70088799-41aae880-1617-11ea-8d8b-ccd2e84eec52.png)
![transmission2](https://user-images.githubusercontent.com/39199872/70088805-440d4280-1617-11ea-8822-9db3fb1b04c5.png)

Apparently white symbolic icons are invisible, perhaps there is a way to make it use only the black ones.

**Comment by clefebvre** [comment]
This is not a bug. Transmission doesn't use symbolic icons, it uses fullcolor ones that's why they don't appear.

*Dark* icon themes are theme precisely for applications like this one, which use fullcolor icons, so that they look good when you're using a Dark GTK theme. In other words, *Dark* icon themes provide white/light fullcolor icons, so it's normal they don't work well with light GTK themes.
